### ISSUE TITLE
Problem with v_gmp install

### ISSUE THREAD

**Issue by blackshirt** [VincentLaisney/v_gmp#1]
Hello, i'm trying to play with this module to do some culprits of cryptography things ..but getting troubles how to install this module correctly. 
Based on readme files, the guides just to `Create a gmp directory in your .vmodules and copy in it the gmp.v and *.h files.`.
Before that, i has been successfully built gmp library under windows within cygwin_64, 
Sure, i have been doing step in the guide, 
```
$ ls ~/.vmodules/gmp
gmp.h  gmp.v  gmp-x86_64.h  libgmp.a
```

but, when i'm trying to test the code, its nof found "gmp.h" header
```
$ v -stats test curve25519_test.v 
---- Testing... --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
builder error: 'gmp.h' not found
---------------------------------------------------------------------------------------------------------------------------------------------------
Failed command 1:    "E:\program\v\v.exe" -stats  -o "C:\Users\reguler\AppData\Local\Temp\v\test_session_1593000\curve25519_test.exe" "C:\Users\reguler\bitbucket\vodcha\curve25519\curve25519_test.v"
Summary for all V _test.v files: 1 failed, 1 total. Runtime: 2891 ms.
```

Any helps for this problem very appreciated ..
Thanks

**Comment by VincentLaisney** [comment]
I do not know where cygwin put the modules of V. I was writing ~/.vmodules for linux.
At the beginning of gmp.v the line
#flag -I @VMODROOT
must include the directory of the module and therefore the gmp.h file.
Search the location of the other modules and put the module at the same place.
The other solution is the change the line of #flag -I @VMODROOT with the full path of the gmp.h of the module (patched) (without the name gmp.h)
Hope it helps

**Comment by VincentLaisney** [comment]
I have done this as a quick job for a specific problem. I intend to continue it but I am busy now.
I have tested the main functions. 
If you find problems with some cryptographic function, tell me.

**Comment by blackshirt** [comment]
> I do not know where cygwin put the modules of V. I was writing ~/.vmodules for linux.
> At the beginning of gmp.v the line
> #flag -I @VMODROOT
> must include the directory of the module and therefore the gmp.h file.
> Search the location of the other modules and put the module at the same place.
> The other solution is the change the line of #flag -I @VMODROOT with the full path of the gmp.h of the module (patched) (without the name gmp.h)
> Hope it helps

usually, its reside in cygwin /usr/local/include or /usr/local/lib directory ...i'm ensure there is `libgmp.a` file at the `c:\cygwin\usr\local` ..my cygwin install directory

**Comment by VincentLaisney** [comment]
Have you resolve your installation problem?

**Comment by VincentLaisney** [comment]
Use `v doctor` to get all information on your installation

**Comment by blackshirt** [comment]
> Have you resolve your installation problem?
I have resolve my problem within MINGW64 environment, doing rebuilding of gmp lib, build vlang compiler ...
Actually, its only detect when i pass `-cc gcc` flag, its mean using gcc compiler, but not with default tcc compiler ...
Its maybe problem how finding libgmp 
here's the output
```
$ v -stats test curve_test.v
---- Testing... ------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------
==================
C:/msys64/tmp/v/test_session_328800/curve_test.exe.15388629638234012702.tmp.c:19786: warning: unknown escape sequence: '\c'
tcc: error: library 'gmp' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error:
===============
```
and this is when passing using gcc compiler `-cc gcc`
```
$ v -cc gcc -stats test curve_test.v
---- Testing... ------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------
        V  source  code size:      21509 lines,     575151 bytes
generated  target  code size:      19776 lines,     685624 bytes
compilation took: 52123.802 ms, compilation speed: 412 vlines/s
eguleitbucket in: C:msys64home
odchacurvecurve_test.v
      OK    [1/8]    51.680 ms     2 asserts | curve.test_curve_cswap()
      OK    [2/8]     0.407 ms     4 asserts | curve.test_curve_decode_scalar()
      OK    [3/8]     0.273 ms     4 asserts | curve.test_curve_decode_x_coordinate()
      OK    [4/8]     0.418 ms     4 asserts | curve.test_curve_encode_x_coordinate()
      OK    [5/8]    59.133 ms     2 asserts | curve.test_curve_255_scalar_multiply()
      OK    [6/8]    86.416 ms     1 assert  | curve.test_curve_448_scalar_multiply()
      OK    [7/8]    71.455 ms     2 asserts | curve.test_curve_x25519_rfc_vector()
      OK    [8/8]   159.064 ms     2 asserts | curve.test_curve_x448_rfc_vector()
eguleitbucketfor running V tests in "C:msys64home
odchacurvecurve_test.v": 21 passed, 21 total. Runtime: 495 ms.

----------------------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Runtime: 57447 ms.
```

So, still there problems with tcc (or other things, that i dont know)..why its faill found `libgmp.a` library ..even with default `libgmp.a` installation

**Comment by blackshirt** [comment]
i would close this issue, you can open it if needed
